blank_issues_enabled: true
contact_links:
  - name: "ğŸŒŸ Feature Request"
    url: "https://github.com/BlafKing/sd-civitai-browser-plus/discussions/new?category=ideas"
    about: "Feature requests are handled in the Discussions tab under 'Ideas'."
  - name: "â“ Questions"
    url: "https://github.com/BlafKing/sd-civitai-browser-plus/discussions/new?category=q-a"
    about: "If you have questions, please ask them in the Discussions tab under 'Q&A'."
